# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    clientId: '%env(CLIENT_ID)%'
    clientSecret: '%env(CLIENT_SECRET)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Services\AccessTokenProvider:
        arguments:
            $session: '@session.factory'
    App\Services\RefreshTokenProvider:
        arguments:
            $session: '@session.factory'
    App\Services\SpotifyService:
        arguments:
            $accessTokenProvider: '@App\Services\AccessTokenProvider'
            $refreshTokenProvider: '@App\Services\RefreshTokenProvider'
    App\Services\SpotifyApiClient:
        arguments:
            $spotifyClient: '@knpu.oauth2.client.spotify'
    App\Controller\PageController:
        arguments:
            $apiKey: '%env(RAPID_API_KEY)%'
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
