name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy on production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy commands
        uses: appleboy/ssh-action@masters
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script:
            ./deploy.sh